### ISSUE TITLE
Need help for midi

### ISSUE THREAD

**Issue by 4dvn** [BOJIT/Blue-Pill-E-Drums#1]
Hello, can you give me the example code midi controller have 16 buttons and 4 potentiometers from note 36-51 with velocity 127?
Best regards

**Comment by BOJIT** [comment]
Hi, sorry, only just saw this.

The majority of this repo's code is for triggering MIDI notes with velocity based on an analogue input signal (see accompanying article linked from the repo).

The only bit that this code that actual sends MIDI notes is the methods from the USB composite library:
`MIDI.sendNoteOn(1, PAD_NOTES[i], velocity);`

The actual implementation will depend on your hardware layout - for mapping these you can use a similar method to the one used [here](https://github.com/BOJIT/Blue-Pill-Macro-Pad/blob/da3933ddeb1657d2c92876c84044c8dea5af2932/src/main.cpp#L38). Don't know what you mean by mapping potentiometers to notes: perhaps you want MIDI CC.

If you are using the Arduino-STM32 core, then this USB composite library is the most helpful: (https://github.com/arpruss/USBComposite_stm32f1). There are MIDI examples in here.

If you want a more granular/low-level control of USB and USB MIDI, check out [libopencm3](https://github.com/libopencm3/libopencm3).

Cheers,

James
